version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for pipenv
  - package-ecosystem: "pipenv"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Docker Files
  - package-ecosystem: "docker"
    directory: "/docker/"
    schedule:
      interval: "daily"
