{{- range .Values.externalSecrets }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "ppserver.labels" $ | indent 4 }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ $.Values.gcpProject.id | quote }}
  {{- if .type }}
  template:
    type: {{ .type | quote }}
  {{- end }}
  dataFrom:
  {{- range .backendSecretNames }}
    - {{ . }}
  {{- end }}
---
{{- end }}
