SWAGGER_DIR = "swagger"
VOWELS = "aoeiu"
RTL = "rtl"

LESS_OR_EQUAL_TO = "$LESS_OR_EQUAL_TO"
LESS_THAN = "$LESS_THAN"
GREATER_OR_EQUAL_TO = "$GREATER_OR_EQUAL_TO"
GREATER_THAN = "$GREATER_THAN"
VALUE_IN = "$VALUE_IN"
VALUE_NOT_IN = "$VALUE_NOT_IN_ARRAY"
VALUE_EQUALS_TO = "$VALUE_EQUALS_TO"
NOT_EQUAL = "$NOT_EQUAL"

SEC_IN_HOUR = 3600

# in seconds
WEEK = 604800
DAY = 86400
