Check export deployment status
---
tags:
  - export

security:
  - Bearer: []

parameters:
  - in: path
    name: deployment_id
    required: true
    type: string
  - in: path
    name: export_process_id
    required: true
    type: string

responses:
  200:
    description: Status and storage file bucket with key
    schema:
      $ref: '#/definitions/CheckExportTaskStatusResponse'

definitions:

  CheckExportTaskStatusResponse:
    type: object
    properties:
      status:
        type: string
        enum: ["CREATED", "PROCESSING", "DONE", "ERROR"]
      exportData:
        $ref: "#/definitions/ExportResultObject"

  ExportResultObject:
    type: object
    properties:
      bucket:
        type: string
      key:
        type: string
