apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..fullname" . }}
  labels:
{{ include "..labels" . | indent 4 }}
data:
  config.yaml: |-
{{ .Values.config | indent 4 }}
{{- range $name, $value := .Values.env }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | quote }}
{{- end }}
{{- end }}
