{{- if .Values.sealedSecretEnabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: {{ include "..fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ include "..fullname" . }}
      namespace: {{ .Release.Namespace }}
      creationTimestamp: null
    type: Opaque
  encryptedData:
{{- range $name, $value := .Values.secretEnv }}
{{- if not (empty $value) }}
    {{ $name }}: {{ $value }}
{{- end }}
{{- end }}

{{- if .Values.secretFiles.enabled -}}
{{- $fullName := include "..fullname" . -}}
{{- range .Values.secretFiles.secrets }}
{{- if not (empty .content) }}
    {{ .name }}: {{ .content }}
{{- end }}
{{- end }}
{{- end }}

{{- else }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "..fullname" . }}
  labels:
{{ include "..labels" . | indent 4 }}
data:
{{- range $name, $value := .Values.secretEnv }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}

{{- if .Values.secretFiles.enabled -}}
{{- $fullName := include "..fullname" . -}}
{{- range .Values.secretFiles.secrets }}
{{- if not (empty .content) }}
  {{ .name }}: {{ .content | b64enc }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}
