summary: Get list of deployments
tags:
  - deployment
security:
  - Bearer: []
parameters:
  - name: body
    in: body
    description: body
    required: true
    schema:
      $ref: "#/definitions/RetrieveDeploymentsRequest"

responses:
  200:
    description: List of deployments based on skip and limit
    schema:
      $ref: "#/definitions/RetrieveDeploymentsResponse"

definitions:
  RetrieveDeploymentsRequest:
    type: object
    required:
      - skip
      - limit
    properties:
      skip:
        type: integer
        minimum: 0
        example: 0
      limit:
        type: integer
        minimum: 1
        example: 10
      sort:
        type: array
        items:
          $ref: "#/definitions/SortField"
      nameContains:
        type: string
        example: abc
      searchCriteria:
        type: string
        example: b2c
      status:
        type: array
        items:
          type: string
          enum: ["DRAFT", "DEPLOYED", "ARCHIVED"]

  Deployment:
    allOf:
      - $ref: "#/definitions/CreateDeploymentRequest"
      - properties:
          id:
            type: string
            example: "5e84b0dab8dfa268b1180536"
          updateDateTime:
            type: string
            format: date-time
          createDateTime:
            type: string
            format: date-time
          userActivationCode:
            type: string
            example: 12345678
          proxyActivationCode:
            type: string
            example: 12345678
          managerActivationCode:
            type: string
            example: 12345678
          moduleConfigs:
            type: array
            items:
              $ref: "#/definitions/ModuleConfig"
          onboardingConfigs:
            type: array
            items:
              $ref: "#/definitions/OnboardingConfig"
          consent:
            $ref: "#/definitions/Consent"
          econsent:
            $ref: "#/definitions/EConsent"
          labels:
            $ref: "#/definitions/Labels"
          learn:
            $ref: "#/definitions/Learn"
          keyActions:
            type: array
            items:
              $ref: "#/definitions/KeyActionConfig"
          mfaRequired:
            type: boolean
          code:
            type: string
          roles:
            $ref: "#/definitions/roles"
  RetrieveDeploymentsResponse:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/Deployment"
      skip:
        type: integer
        minimum: 0
        example: 0
      limit:
        type: integer
        minimum: 1
        example: 10
      total:
        type: integer
        example: 1000

  Labels:
    type: array
    items:
      $ref: "#/definitions/Label"

  Label:
    properties:
      id:
        type: string
        example: "5d386cc6ff885918d96edb2c"
      text:
        type: string
        example: "Deceased"
      authorId:
        type: string
        example: "5d386cc6ff885918d96edb2c"
      updatedBy:
        type: string
        example: "5d386cc6ff885918d96edb2c"
      createDateTime:
        type: string
        example: "2022-04-12T11:35:21.435000Z"
      updateDateTime:
        type: string
        example: "2022-04-12T11:35:21.435000Z"

  OnboardingConfig:
    type: object
    required:
      - onboardingId
      - order
      - userTypes
    properties:
      id:
        type: string
        example: "5e84b0dab8dfa268b1180536"
      onboardingId:
        type: string
        example: EConsent
      status:
        $ref: "#/definitions/EnableStatus"
      configBody:
        type: object
        description: could be any dictionary
      order:
        type: integer
      version:
        type: integer
      userTypes:
        type: array
        items:
          type: string
          enum: [User, Proxy]
