apiVersion: v2
appVersion: 1.23.0
description: Huma Server SDK with required storage
home: https://huma.com/
kubeVersion: ">=1.19.0-0"
keywords:
  - huma
  - server
  - backend
  - redis
  - mongodb-user
  - bucket
maintainers:
  - name: Denis Trofimov
    email: denis.trofimov@huma.com
name: huma-server-sdk
sources:
  - https://github.com/huma-engineering/huma-server-sdk
type: application
version: 0.9.0
